[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$major.$minor.$patch$prerelease"
version = "0.10.1"
version_files = [
    "naas/__init__.py",
    "naas/runner/runner.py",
    ".cz.toml",
    "setup.py:version",
    "Dockerfile"
]
